apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: mern-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mern-microservices-lean-rebuilt-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: mern-ecommerce
spec:
  selector:
    app: auth
  ports:
    - port: 3001
      targetPort: 3001
      name: http
