apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: mern-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: mern-microservices-lean-rebuilt-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: mern-ecommerce
spec:
  selector:
    app: catalog
  ports:
    - port: 3002
      targetPort: 3002
      name: http
