apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: mern-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mern-microservices-lean-rebuilt-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE
              value: "http://gateway:8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: mern-ecommerce
spec:
  selector:
    app: client
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      name: http
  type: ClusterIP
