apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: mern-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: mern-microservices-lean-rebuilt-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth:3001"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog:3002"
            - name: CART_SERVICE_URL
              value: "http://cart:3003"
            - name: ORDER_SERVICE_URL
              value: "http://order:3004"
            - name: SHIPPING_SERVICE_URL
              value: "http://shipping:3005"
            - name: CLIENT_URL
              value: "http://client:5173"
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: mern-ecommerce
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
