apiVersion: apps/v1
kind: Deployment
metadata: { name: mongo, namespace: shop }
spec:
  replicas: 1
  selector: { matchLabels: { app: mongo } }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports: [{ containerPort: 27017 }]
          args: ["--bind_ip_all"]
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata: { name: mongo, namespace: shop }
spec:
  selector: { app: mongo }
  ports: [{ port: 27017, targetPort: 27017 }]
