apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: mern-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mern-microservices-lean-rebuilt-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: ORDER_PORT
              value: "3004"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/mern"
            - name: RABBIT_URL
              value: "amqp://user:pass@rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: mern-ecommerce
spec:
  selector:
    app: order
  ports:
    - port: 3004
      targetPort: 3004
