apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: mern-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: mern-microservices-lean-rebuilt-shipping:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: SHIPPING_PORT
              value: "3005"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/mern"
            - name: AMQP_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: RABBIT_URL
              value: "amqp://guest:guest@rabbitmq:5672"
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: mern-ecommerce
spec:
  selector:
    app: shipping
  ports:
    - port: 3005
      targetPort: 3005
      name: http
